export const TRANSLATE = {
  full_moon: "Cheia",
  crescent_moon: "Crescente",
  waning_moon: "Minguante",
  new_moon: "Nova",
  river: "Rio",
  lake: "Lago",
  dam: "Represa",
  high_seas: "Alto mar",
  coastal: "Costeira",
  mangrove: "Mangue",
  natual_baits: "Iscas naturais",
  artificial_baits: "Iscas artificiais",
  fly_fishing: "Mosca (fly fishing)",
  vertical_fishing: "Pesca vertical",
  multifilament: "Multifilamento",
  monofilament: "Monofilamento",
  millimeter: "Milímetro",
  librarians: "Libragens",
  reel: "Molinete",
  roulette: "Carretilha",
  fly_fishing_line: "Linha para Fly (mosca)",
  flying_equipment: "Equipamento para Fly (mosca)",
  fish_and_pay: "Pesque e Pague",
  full_river: "Cheia",
  low_river: "Na caixa",
  river_in_drought: "Seca",
  high_tide: "Alta",
  low_tide: "Baixa",
  aerial: "Aéreo",
  terrestrial: "Terrestre",
  aerial_and_terrestrial: "Aéreo e terrestre",
  hotel: "Hotel",
  boat_hotel: "Barco hotel",
  camping: "Acampamento",
  inn: "Pousada"
};
